---
title: "Teaching"
pagetitle: "Sanval's Teaching"
---

***

## Colby College

Challenges of the Anthropocene: Views from the Global South (EC468): Spring 2025, 2023

Econometrics (EC393): Spring 2025, 2023

Environmental and Natural Resource Economics (EC231): Fall 2025, 2024, 2022

Challenges of the Anthropocene: Views from the Global South (EC468): Spring 2025; 2023

Econometrics (EC393): Spring 2025; 2023

Environmental and Natural Resource Economics (EC231): Fall 2024; 2022

***

## Lahore University of Management Sciences (LUMS)

Introduction to Environmental Economics (ECON 244): Fall 2017, 2016; Spring 2022, 2021, 2020

Mathematical Applications in Economics (ECON 262): Fall 2021, 2020, 2019; 2018; Spring 2017

Advanced Environmental and Natural Resource Economics (ECON 3420): Fall 2017

Topics in Environmental and Natural Resource Economics (ECON 440): Spring 2018

Principles of Macroeconomics (ECON 121): Spring 2019

A Survey of the History of Economic Thought (ECON 201): Fall 2020

***

## University of California, Riverside

Introduction to Environmental Economics (ENSC 006): Fall 2014, 2013, *teaching assistant to Prof. Ariel Dinar*

Introduction to Environmental Sciences (ENSC 003): Spring 2012, *teaching assistant to Prof. David Crohn*

***

## Pre Grad School

Many years ago, when I was a senior at Colby College, I worked as an Economics Tutor to help students grasp concepts covered in their principles courses. I consider this my first foray into teaching.

***